config/routes.rb
Rails.application.routes.draw do

  resources :team do
    resources :orders
  end

  devise_for :users,
    path_names: {
      sign_in: "login",
      sign_out: "logout"
    }

  root 'team#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :team
  has_many :user_order_costs
  has_many :users, through: :user_order_costs
end

app/models/team.rb
class Team < ActiveRecord::Base
  validates :name, presence: true
  before_create :default_balance

  has_many :user_team_balances, dependent: :delete_all
  has_many :users, through: :user_team_balances
  has_many :orders

  private

  def default_balance
    self.balance = 0.0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_team_balances, dependent: :delete_all
  has_many :teams, through: :user_team_balances

  has_many :user_order_costs, dependent: :delete_all
  has_many :orders, through: :user_order_costs

  scope :all_except, ->(user) { where.not(id: user) }
end

app/models/user_order_cost.rb
class UserOrderCost < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
end

app/models/user_team_balance.rb
class UserTeamBalance < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :fetch_team
  before_action :fetch_order, only: [:show]
  helper_method :order_cost

  def show
  end

  def new
    @order = @team.orders.build
  end

  def create
    @order = @team.orders.build(order_params)
    if @order.save
      redirect_to [@team, @order]
    else
      render "new"
    end
  end

  def destroy
    @order.destroy
    redirect_to root_path
  end

  private

    def order_params
      params.require(:order).permit()
    end

    def fetch_order
      @order = Order.find(params[:id])
    end

    def fetch_team
      @team = Team.find(params[:team_id])
    end

    def order_cost(user)
      @order.user_order_costs.find_by(user: user).cost
    end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  before_action :authenticate_user!
  helper_method :current_user_balance, :current_user_cost

  def index
    @teams = current_user.teams
  end

  def show
    @orders = current_team.orders
  end

  def new
    all_users_except_current
  end

  def edit
    current_team
    @users = User.all
  end

  def create
    @team = current_user.teams.create(team_params)
    if @team.save
      redirect_to @team
    else
      all_users_except_current
      render "new"
    end
  end

  def update
    if current_team.update(team_params)
      redirect_to @team
    else
      all_users_except_current
      render "edit"
    end
  end

  def destroy
    current_team.destroy
    redirect_to root_path
  end

  private

  def team_params
    params.require(:team).permit(:name, user_ids: [])
  end

  def all_users_except_current
    @users ||= User.all_except(current_user)
  end

  def current_team
    @team ||= Team.find(params[:id])
  end

  def current_user_balance(team)
    team.user_team_balances.find_by(current_user.id).balance
  end

  def current_user_cost(order)
    user_order_costs = order.user_order_costs.find_by(current_user.id)
    user_order_costs ? user_order_costs.cost : "0.00"
  end

end

app/controllers/user_teams_controller.rb
class UserTeamsController < ApplicationController
  before_action :authenticate_user!

  def index
    @teams = User.find(current_user.id).teams
    @user_team_balances = UserTeamBalance.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> -->
      <%= link_to "Manolios", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manolios</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "navbar" %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/orders/new.html.erb
<h1 class="page-header">New Order</h1>

<%= form_for [@team,@order] do |f| %>

  <% @team.users.each do |user| %>
    <%= user.email %>
  <% end %>

  <%= f.submit class:"btn btn-default" %>
<% end %>

app/views/orders/show.html.erb
<h3>
  <%= @order.team.name %> / <%= l(@order.created_at, format: :short) %> - <%= @order.cost %> €
</h3>

<table class="table">
  <thead>
    <tr>
        <% @order.team.users.each do |user| %>
      		<th> <%= user.first_name %> <%=user.last_name %> </th>
  		<% end %>
    </tr>
  </thead>
  <tbody>
  	<tr>
        <% @order.team.users.each do |user| %>
      		<th> <%= order_cost(user) %> </th>
  		<% end %>
    </tr>
  </tbody>
</table>

app/views/team/edit.html.erb
<div class="row">
  <h1 class="page-header">Edit <%= @team.name %></h1>

  <%= form_for (@team), html: {class: "col-sm-4"} do |f| %>
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <label> Select users </label>
      <%= collection_check_boxes(:team, :user_ids, @users, :id, :email) do |b| %>
        <div class="checkbox">
          <%= b.label { b.check_box(class: "checkbox") + b.text } %>
        </div>
      <% end %>
    </div>

      <%= f.submit class: "btn btn-default" %>
  <% end %>
</div>

<div class="row col-sm-4 clearfix">
  <%= link_to "Back", team_path(id: @team.id) %>
</div>

app/views/team/index.html.erb
<h1 class="page-header">Your Teams</h1>

<table class="table">
  <thead>
    <tr>
      <th>Team</th>
      <th>Team Balance</th>
      <th>Your Balance</th>
    </tr>
  </thead>
  <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td><%= link_to team.name, team_path(id: team.id) %></td>
        <td><%= team.balance %></td>
        <td><%= current_user_balance(team) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pull-right clearfix">
  <%= link_to "New Team", new_team_path, class: "btn btn-default" %>
</div>

app/views/team/new.html.erb
<h1 class="page-header">New Team</h1>

<%= form_for :team, url: team_index_path, html: {class: 'col-sm-4'}  do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Select users</label>
    <%= collection_check_boxes(:team, :user_ids, @users, :id, :email) do |b| %>
      <div class="checkbox">
        <%= b.label { b.check_box(class: "checkbox") + b.text } %>
      </div>
    <% end %>
  </div>

  <%= f.submit class:"btn btn-default" %>
<% end %>

app/views/team/show.html.erb
<h3>
	<%= @team.name %> - <%= @team.balance %> €
</h3>
<p>
	<%= link_to "Edit", edit_team_path(@team) %> |
	<%= link_to "Destroy", team_path(@team),
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>

<h3> Orders </h3>
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Order Cost</th>
      <th>Your Cost</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to l(order.created_at, format: :short), team_order_path(@team, order) %></td>
        <td><%= order.cost %></td>
        <td><%= current_user_cost(order) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pull-right clearfix">
  <%= link_to "New Order", new_team_order_path(@team), class: "btn btn-default" %>
</div>

app/views/user_teams/index.html.erb
<h2> Your Teams</h2>

<table>
  <tr>
    <th>Team</th>
    <th>Team Balance</th>
    <th>Your Balance</th>
  </tr>
  <% @teams.each do |team| %>
    <tr>
      <td> <%= team.name %> </td>
      <td> <%= team.balance %> </td>
      <td> <%= team.user_team_balances.first.balance %> </td>
    </tr>
  <% end %>
</table>